export enum TransactionType {
  CLASSIC = 0,
  PROVIDER_REGISTRATION = 1,
  PROVIDER_UPDATE_SERVICE = 2,
  PROVIDER_UPDATE_REGISTRAR = 3,
  PROVIDER_UPDATE_REVOCATION = 4,
  COINBASE = 5,
  QUORUM_COMMITMENT = 6,
  MASTERNODE_HARD_FORK_SIGNAL = 7,
  ASSET_LOCK = 8,
  ASSET_UNLOCK = 9,
}